#!/usr/bin/env bash
set -e
BASE="http://127.0.0.1:8123"
OUT="_raw"

get() {
  local jar="$1" path="$2" slug="$3"
  curl -s -b "$jar" "$BASE$path" -o "$OUT/$slug.html"
  echo "  fetched $slug  <-  $path"
}

echo "== guest =="
get "" "/" "index"
get "" "/about" "about"
get "" "/availability" "availability"
get "" "/availability?type=function_hall" "availability-hall"
get "" "/events" "events"
get "" "/events/1" "event-1"
get "" "/login" "login"
get "" "/register" "register"
get "" "/forgot-password" "forgot-password"

echo "== customer (marco.v) =="
get "customer.jar" "/dashboard" "dashboard"
get "customer.jar" "/profile" "profile"
get "customer.jar" "/reserve" "reserve"
get "customer.jar" "/reserve/court" "reserve-court"
get "customer.jar" "/reserve/hall" "reserve-hall"
get "customer.jar" "/reservations" "reservations"
get "customer.jar" "/reservations?filter=past" "reservations-past"
get "customer.jar" "/reservations/MDC-2026-000022" "reservation-detail"
get "customer.jar" "/matching" "matching"
get "customer.jar" "/matching/results" "matching-results"
get "customer.jar" "/notifications" "notifications"

echo "== admin =="
get "admin.jar" "/admin" "admin-dashboard"
get "admin.jar" "/admin/reservations" "admin-reservations"
get "admin.jar" "/admin/reservations/10" "admin-reservation-pending"
get "admin.jar" "/admin/reservations/24" "admin-reservation-approved"
get "admin.jar" "/admin/reservations/create" "admin-reservation-create"
get "admin.jar" "/admin/schedules" "admin-schedules"
get "admin.jar" "/admin/players" "admin-players"
get "admin.jar" "/admin/players/1" "admin-player-online"
get "admin.jar" "/admin/players/9" "admin-player-walkin"
get "admin.jar" "/admin/players/walk-in" "admin-walkin"
get "admin.jar" "/admin/matching" "admin-matching"
get "admin.jar" "/admin/matching/1" "admin-matching-generated"
get "admin.jar" "/admin/matching/4" "admin-matching-open"
get "admin.jar" "/admin/matching/create" "admin-matching-create"
get "admin.jar" "/admin/events" "admin-events"
get "admin.jar" "/admin/events/1" "admin-event-detail"
get "admin.jar" "/admin/events/create" "admin-event-create"
get "admin.jar" "/admin/payments" "admin-payments"
get "admin.jar" "/admin/reports" "admin-reports"
get "admin.jar" "/admin/reports/reservation" "admin-report-reservation"
get "admin.jar" "/admin/reports/utilisation" "admin-report-utilisation"
get "admin.jar" "/admin/reports/event" "admin-report-event"
get "admin.jar" "/admin/reports/payment" "admin-report-payment"
get "admin.jar" "/admin/reports/player" "admin-report-player"
get "admin.jar" "/admin/courts" "admin-courts"
get "admin.jar" "/admin/courts/1/edit" "admin-court-edit"
get "admin.jar" "/admin/halls" "admin-halls"
get "admin.jar" "/admin/users" "admin-users"
get "admin.jar" "/admin/settings" "admin-settings"
get "admin.jar" "/admin/logs" "admin-logs"
get "admin.jar" "/admin/notifications" "admin-notifications"

echo "done"
